import type { NextPage } from "next";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css"
import { Livro } from "@/classes/modelo/Livro";
import { LinhaLivro } from "@/componentes/LinhaLivro";
import { Menu } from "@/componentes/Menu";
import Head from "next/head";
import { ControleLivros } from "@/classes/controle/ControleLivros";

const LivroLista: NextPage = () => {
    const [livros, setLivros] = useState<Array<Livro>>([]);
    const [carregado, setCarregado] = useState(false);
    const controleLivros = new ControleLivros();

    useEffect(() => {
        controleLivros.obterLivros().then((livros) => {
            setLivros(livros);
            setCarregado(true);
        });
    }, [carregado]);

    const excluir = async (codigo: string) => {
        await controleLivros.excluir(codigo)
        .then(() => {
            setCarregado(false);
        });        
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Menu />
            <main className={`${styles.main}`}>
                <h1 className={`${styles.title} display-2`}>Catálogo</h1>
                <table className="table table-striped">
                    <thead className="table-dark">
                        <tr>
                            <th scope="col" className="col-2">Título</th>
                            <th scope="col">Resumo</th>
                            <th scope="col" className="col-2">Editora</th>
                            <th scope="col" className="col-2">Autores</th>
                        </tr>
                    </thead>
                    <tbody>
                        {livros.map((livro, index) => (
                            <LinhaLivro key={index} livro={livro} excluir={() => excluir(livro.codigo)} />
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    );
};

export default LivroLista;